services:
  gate_group:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gate_group
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge